# -*- coding: utf-8 -*-
"""Casestudy10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ms6-4hBwFgikNnYp8jzKKZY2fzoolOtB
"""

c1=float(input("Enter the cost of item 1: "))
c2=float(input("Enter the cost of item 2: "))
c3=float(input("Enter the cost of item 3: "))
tc=c1+c2+c3
if tc>50:
  tc=tc-(0.1*tc)
print("Total cost :",tc)